-keep class kr.cosine.groupfinder.data.model.** { *; }
-keepclassmembers class kr.cosine.groupfinder.data.model.** { *; }
-keep,allowobfuscation,allowshrinking interface retrofit2.Call
-keep,allowobfuscation,allowshrinking class retrofit2.Response
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation